# backend/app/api/npc_routes.py

from fastapi import APIRouter
from backend.app.timeline.reaction_store import get_latest_reactions

router = APIRouter(
    prefix="/npc",
    tags=["npc"],
)

@router.get("/reactions/latest")
def get_latest_npc_reactions():
    """
    Returns the most recent NPC reactions generated by timeline events.
    """
    return get_latest_reactions()
